name: Publish - AUR

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag-name:
        description: Version tag to publish to the AUR
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  aur:
    name: Update AUR package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        #with:
        #  ref: ${{ github.event.inputs.tag-name || github.ref_name }}

      - name: Generate PKGBUILD
        run: |
          mkdir -pv build
          scripts/create-PKGBUILD.sh ${{ github.event.inputs.tag-name || github.ref_name }} >build/PKGBUILD

      - name: Publish PKGBUILD to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: pretty-php
          pkgbuild: build/PKGBUILD
          updpkgsums: true
          test: true
          test_flags: --clean --cleanbuild --syncdeps --noconfirm
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ github.event.inputs.tag-name || github.ref_name }}
          allow_empty_commits: false
