name: Check CI runs

on:
  workflow_call:
    inputs:
      ci_workflow:
        description: CI workflow name
        type: string
        required: true
    outputs:
      ci_required:
        description: "Whether a CI workflow run is required for the current tree (0 = no, 1 = yes)"
        value: ${{ jobs.check-ci-runs.outputs.ci_required }}

jobs:
  check-ci-runs:
    name: Check CI workflow runs
    runs-on: ubuntu-latest
    outputs:
      ci_required: ${{ steps.get-ci-required.outputs.ci_required }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for a successful run with the same tree
        id: get-ci-required
        shell: bash
        run: |
          ci_required=1
          mapfile -t pathspec < <([[ -f .ci-pathspec ]] && sed -E $'/^[ \t]*(#|$)/d' .ci-pathspec)
          while read -r ref; do
              git diff-tree --quiet "$ref" HEAD -- ${pathspec+"${pathspec[@]}"} || continue
              printf '%s workflow already succeeded with the same tree: %s\n' "$ci_workflow" "$ref"
              ci_required=0
              break
          done < <(
              git rev-list --no-merges HEAD |
                  grep -Fxf <(gh run list --workflow "$ci_workflow" --status success --json headSha --jq '.[].headSha')
          )
          ((!ci_required)) || printf 'No successful %s workflow runs found with the same tree\n' "$ci_workflow"
          printf 'ci_required=%d\n' "$ci_required" | tee -a "$GITHUB_OUTPUT"
        env:
          ci_workflow: ${{ inputs.ci_workflow }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
