name: Release

on:
  push:
    tags:
      - "v[0-9]*"

jobs:
  release:
    name: Build phar and create draft release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run build script
        run: |
          scripts/build.sh ${{ github.ref_name }}
          { printf 'artifact_name=%s\n' "${GITHUB_REPOSITORY##*/}" &&
            printf 'artifact_path=%s\n' build/dist/* | head -n1; } >>"$GITHUB_ENV"

      - name: Create draft release
        run: |
          ${{ env.artifact_path }} --version | grep -F '${{ env.artifact_name }} ${{ github.ref_name }}-'
          gh release create ${{ github.ref_name }} ${{ env.artifact_path }} --draft --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
