name: Release

on:
  push:
    tags:
      - "v[0-9]*"

jobs:
  release:
    name: Build phar and release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run build script
        run: |
          scripts/build.sh --phar ${{ github.ref_name }}
          jq -r '{"artifact_name":.package,"artifact_path":.assets[]|select(.type=="phar")|.path}|to_entries[]|"\(.key)=\(.value)"' build/dist/manifest.json >>$GITHUB_ENV

      - name: Create draft release
        run: |
          mv -f build/dist/${{ env.artifact_path }} build/dist/${{ env.artifact_name }}.phar
          build/dist/${{ env.artifact_name }}.phar --version | grep -F '${{ env.artifact_name }} ${{ github.ref_name }}-'
          gh release create ${{ github.ref_name }} build/dist/${{ env.artifact_name }}.phar --draft --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
